### index of api returns basic information about api in response
GET http://127.0.0.1:8000/api/index HTTP/1.1

### Register new user with email and password
POST http://127.0.0.1:8000/api/auth/register HTTP/1.1
content-type: application/json

{
  "email": "your_email@gmail.com",
  "password": "your_password"
}

### Login user with email and password
POST http://127.0.0.1:8000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "your_email@gmail.com",
  "password": "your_password"
}

### Ping user (validate user jwt)
POST http://127.0.0.1:8000/api/auth/ping HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJlNzgyM2VmMDFiZDRkMmI5NjI3NDE2NThkMjA4MDdlZmVlNmRlNWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZGVybS1kZXRlY3QtMjcyIiwiYXVkIjoiZGVybS1kZXRlY3QtMjcyIiwiYXV0aF90aW1lIjoxNzAyOTIxNTI4LCJ1c2VyX2lkIjoiWlJJR3lIZzdGeFlwODBKN0daeFlUclprU0wzMiIsInN1YiI6IlpSSUd5SGc3RnhZcDgwSjdHWnhZVHJaa1NMMzIiLCJpYXQiOjE3MDI5MjE1MjgsImV4cCI6MTcwMjkyNTEyOCwiZW1haWwiOiJ5b3VyX2VtYWlsQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ5b3VyX2VtYWlsQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.DFFcKfk0dVieESPCQPP8D66dS7M9n-3_2ziIfbRAdgcRpdbSCthpQCPcTgX_P-UcmuMUqg1BcT9Y__rE3sZlJDFgSm4bkWYDD8L1dE-gR4fJUfGlVwAMZ1uj_EdMQTbwnK9xQ3QQrQcj1nlBG2PXiArY5CDcPWkvSYLfWHi47rlLhkMJ56r8jq8Myv8Wt3EjnjYPti3a8_iDqLDqIa7YEsuVKS8Lfa1PFbGkL2q78lU5K4tbZXZCkRDOzLtwVSWVrZ38f7wHcnkNgNh_eJePkXf82wS4-7Z-1sASCAKFcedcdngJtvDM7sKfLcV_zc0xBkf6GhiFy__88wb-nDC64A